"""LaTeX build pipeline.

Converts a paper's markdown to a venue-style .tex file, then compiles
it with :mod:`pdflatex` to ``paper.pdf``. We default to the
``acmart`` class (ships with TeX Live) in ``sigconf`` mode, which is
the format used by NeurIPS, ICML, and most CS conferences.

The .tex file is generated by walking the markdown structure
(headings, lists, paragraphs, citations) and emitting the matching
LaTeX. It is intentionally minimal: it does NOT try to support every
markdown feature. Unsupported features degrade to a paragraph with
the markdown text verbatim.

The LaTeX file is written to ``workspace/paper/body/paper.tex`` and
the PDF to ``workspace/paper/body/paper.pdf``.
"""

from __future__ import annotations

import logging
import re
import shutil
import subprocess
from pathlib import Path
from typing import Iterable

logger = logging.getLogger(__name__)


# ---- Preamble templates --------------------------------------------------


# NOTE: \ccsdesc takes ONE mandatory argument. The earlier
# ``\ccsdesc{}{...}`` form printed the concept as body text BEFORE
# \maketitle, which silently broke acmart's topmatter (no title, no
# abstract on page 1). Verified against acmart 2.18 on 2026-07-16.
NEURIPS_PREAMBLE_TEMPLATE = r"""\documentclass[sigconf,nonatbib]{acmart}
\settopmatter{printacmref=false, printccs=true, printfolios=true}
\setcopyright{none}
\usepackage{balance}
\begin{document}
\title{%s}
\author{Paperfessor Agent Group}
\affiliation{\institution{Paperfessor}\city{}\state{}\country{}}
\email{research@paperfessor.local}
\begin{abstract}
%s
\end{abstract}
\ccsdesc[500]{Computing methodologies~Machine learning}
\keywords{anomaly detection, self-supervised learning, time series, contrastive learning}
\maketitle
%% Overfull-line protection: long identifiers (dataset names, code
%% spans) must never cross the column edge.
\sloppy
\emergencystretch=3em
"""

# Backwards-compat alias: existing code may import the old name.
NEURIPS_PREAMBLE = NEURIPS_PREAMBLE_TEMPLATE

# Some venues (NeurIPS, ICML, ICLR) use a near-identical ACM 2-column
# layout, so acmart is a faithful stand-in. Other venues (CVPR, ACL,
# AAAI) have their own .cls files that we do not bundle; the
# ``acmart [sigconf]`` layout is the closest visual match we can ship
# without a per-venue .cls. We note the target venue in the title
# so the user knows the paper is "submitted to" the right venue.

_VENUE_NOTE: dict[str, str] = {
    "s4210200925": "Submitted to the 31st ACM SIGKDD Conference on Knowledge Discovery and Data Mining (KDD '26)",
    "s4210196385": "Submitted to the AAAI Conference on Artificial Intelligence (AAAI '26)",
    "s4210191938": "Submitted to the International Joint Conference on Artificial Intelligence (IJCAI '26)",
    "s4210224017": "Submitted to the Conference on Uncertainty in Artificial Intelligence (UAI '26)",
    "s4210197613": "Submitted to the International Conference on Artificial Intelligence and Statistics (AISTATS '26)",
    "s4210226001": "Submitted to the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR '26)",
    "s4210205404": "Submitted to the IEEE/CVF International Conference on Computer Vision (ICCV '26)",
    "s4210198630": "Submitted to the European Conference on Computer Vision (ECCV '26)",
    "s4210212456": "Submitted to the Annual Meeting of the Association for Computational Linguistics (ACL '26)",
    "s4210225364": "Submitted to the Conference on Empirical Methods in Natural Language Processing (EMNLP '26)",
    "s4210223919": "Submitted to the Conference of the North American Chapter of the ACL (NAACL '26)",
    "s4210195363": "Submitted to the Conference on Neural Information Processing Systems (NeurIPS '26)",
    "s4306419644": "Submitted to the International Conference on Machine Learning (ICML '26)",
    "s4210172783": "Submitted to the International Conference on Learning Representations (ICLR '26)",
    "s4210197765": "Submitted to the IEEE International Conference on Robotics and Automation (ICRA '26)",
    "s4210221676": "Submitted to the IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS '26)",
}


# ---- LaTeX preamble templates per class ---------------------------------

# A preamble for any class the user / venue_index picks. The
# caller is responsible for ensuring the class file is available
# (downloaded by the PhD to workspace/paper/templates/ or provided
# by the TeX Live install).
def _preamble_for_class(class_name: str) -> str:
    """Return the LaTeX preamble snippet for ``class_name``.

    For ACM-aligned classes we use acmart [sigconf] as the
    canonical 2-column layout. For everything else, the class
    file is expected to be in the build directory; we just emit
    a generic \\documentclass line.
    """
    if class_name == "acmart-sigconf":
        return NEURIPS_PREAMBLE_TEMPLATE
    # Generic preamble: caller is responsible for the class file
    # being present at build time.
    return (
        "\\documentclass[10pt]{%s}\n"
        "\\usepackage[utf8]{inputenc}\n"
        "\\usepackage[T1]{fontenc}\n"
        "\\usepackage{graphicx}\n"
        "\\title{%s}\n"
        "\\author{Paperfessor Agent Group}\n"
        "\\date{\\today}\n"
        "\\begin{document}\n"
        "\\maketitle\n"
        "\\begin{abstract}\n%s\\end{abstract}\n"
    )

# Backwards-compat alias: existing code may import the old name.
NEURIPS_PREAMBLE = NEURIPS_PREAMBLE_TEMPLATE

# Some venues (NeurIPS, ICML, ICLR) use a near-identical ACM 2-column
# layout, so acmart is a faithful stand-in. Other venues (CVPR, ACL,
# AAAI) have their own .cls files that we do not bundle; the
# ``acmart [sigconf]`` layout is the closest visual match we can ship
# without a per-venue .cls. We note the target venue in the title
# so the user knows the paper is "submitted to" the right venue.

_VENUE_NOTE: dict[str, str] = {
    # ACM conferences
    "s4210200925": "Submitted to the 31st ACM SIGKDD Conference on Knowledge Discovery and Data Mining (KDD '26)",
    "s4210196385": "Submitted to the AAAI Conference on Artificial Intelligence (AAAI '26)",
    "s4210191938": "Submitted to the International Joint Conference on Artificial Intelligence (IJCAI '26)",
    "s4210224017": "Submitted to the Conference on Uncertainty in Artificial Intelligence (UAI '26)",
    "s4210197613": "Submitted to the International Conference on Artificial Intelligence and Statistics (AISTATS '26)",
    "s4210226001": "Submitted to the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR '26)",
    "s4210205404": "Submitted to the IEEE/CVF International Conference on Computer Vision (ICCV '26)",
    "s4210198630": "Submitted to the European Conference on Computer Vision (ECCV '26)",
    "s4210212456": "Submitted to the Annual Meeting of the Association for Computational Linguistics (ACL '26)",
    "s4210225364": "Submitted to the Conference on Empirical Methods in Natural Language Processing (EMNLP '26)",
    "s4210223919": "Submitted to the Conference of the North American Chapter of the ACL (NAACL '26)",
    "s4210195363": "Submitted to the Conference on Neural Information Processing Systems (NeurIPS '26)",
    "s4306419644": "Submitted to the International Conference on Machine Learning (ICML '26)",
    "s4210172783": "Submitted to the International Conference on Learning Representations (ICLR '26)",
    "s4210197765": "Submitted to the IEEE International Conference on Robotics and Automation (ICRA '26)",
    "s4210221676": "Submitted to the IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS '26)",
}

NEURIPS_TAIL = r"""
\bibliographystyle{ACM-Reference-Format}
\bibliography{refs}
\end{document}
"""


# ---- Markdown -> LaTeX converter -----------------------------------------


def _escape(s: str) -> str:
    """Escape LaTeX special characters in plain text only.

    Designed to be applied to text that does NOT yet contain LaTeX
    commands. It walks the string and only escapes parts that are
    NOT inside a ``\\command{...}`` block. This way the LaTeX
    commands we generate upstream survive the escape. It also
    leaves ``_`` and ``^`` untouched when they are LaTeX
    subscript / superscript operators (i.e. preceded by a ``}`` or
    another ``_`` / ``^`` / alnum / command).
    """
    out: list[str] = []
    i = 0
    while i < len(s):
        c = s[i]
        if c == "\\" and i + 1 < len(s) and (s[i + 1].isalpha() or s[i + 1] in "_"):
            # Possible LaTeX command. Copy as-is until the matching
            # brace pair (if any) is closed.
            j = i + 1
            while j < len(s) and (s[j].isalpha() or s[j] in "_"):
                j += 1
            cmd = s[i:j]
            out.append(cmd)
            # If the command is followed by brace groups, preserve
            # them. We support up to three groups: e.g. ``\frac{a}{b}``
            # (two) and ``_{X}`` (one) — three is enough to walk
            # past a LaTeX subscript whose argument itself uses
            # ``\command{...}``.
            for _ in range(3):
                if j < len(s) and s[j] == "{":
                    depth = 1
                    k = j + 1
                    while k < len(s) and depth > 0:
                        if s[k] == "{":
                            depth += 1
                        elif s[k] == "}":
                            depth -= 1
                        k += 1
                    out.append(s[j:k])
                    j = k
            # Also consume any trailing `}` that closes a wrapping
            # subscript or superscript the LLM emitted.
            while j < len(s) and s[j] == "}":
                out.append(s[j])
                j += 1
            i = j
            continue
        # NOTE: real inline math ($...$) is stashed before this pass,
        # so any remaining `_` / `^` is TEXT-mode content and must be
        # escaped unconditionally. (The old subscript heuristic left
        # `x_i` raw and killed the pdflatex build: "Missing $ inserted"
        # at \texttt{x_i}, observed 2026-07-16.)
        if c == "&":
            out.append(r"\&")
        elif c == "%":
            out.append(r"\%")
        elif c == "$":
            out.append(r"\$")
        elif c == "#":
            out.append(r"\#")
        elif c == "_":
            out.append(r"\_")
        elif c == "{":
            out.append(r"\{")
        elif c == "}":
            out.append(r"\}")
        elif c == "~":
            out.append(r"\textasciitilde{}")
        elif c == "^":
            out.append(r"\textasciicircum{}")
        elif c == "\\":
            out.append(r"\textbackslash{}")
        else:
            out.append(c)
        i += 1
    return "".join(out)


def _md_inline_to_tex(s: str) -> str:
    """Convert inline markdown to LaTeX. The escape is done first,
    THEN we wrap the (now-safe) parts in LaTeX commands.

    Also translates common Unicode math / dashes to their LaTeX
    counterparts so the acmart preamble does not need extra
    ``\\DeclareUnicodeCharacter`` rules.

    Inline math (``$...$``) is preserved as-is (the inner $ must
    not be escaped) so the LLM can emit ``$f_\\theta$`` and we
    pass it through to LaTeX verbatim.
    """
    # Common Unicode -> LaTeX translations. The LLM often emits
    # ≥/≤/≠/×/—/–; acmart's defaults don't include them.
    # Math-only commands must be wrapped in $...$ \u2014 bare \pm / \geq
    # in text mode force LaTeX into math mode and swallow the
    # following spaces (observed: caption "\u00b195%CIover3seeds").
    s = s.replace("\u2265", r"$\geq$")
    s = s.replace("\u2264", r"$\leq$")
    s = s.replace("\u2260", r"$\neq$")
    s = s.replace("\u00d7", r"$\times$")
    s = s.replace("\u2014", "---")
    s = s.replace("\u2013", "--")
    s = s.replace("\u00b1", r"$\pm$")
    s = s.replace("\u2026", r"\ldots{}")
    # Preserve inline math $...$ so the inner $ is not escaped.
    math_segments: list[str] = []

    def stash_math(m: re.Match) -> str:
        math_segments.append(m.group(0))
        return f"\x00M{len(math_segments) - 1}\x00m"

    s = re.sub(r"\$[^$]+\$", stash_math, s)
    # Bold: **text** -> keep as is for now, we'll wrap after escape
    s = re.sub(r"\*\*(.+?)\*\*", lambda m: "\x00B" + m.group(1) + "\x00b", s)
    # Italic: *text* -> marker
    s = re.sub(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)",
               lambda m: "\x00I" + m.group(1) + "\x00i", s)
    # Inline code: `text` -> marker
    s = re.sub(r"`([^`]+)`", lambda m: "\x00C" + m.group(1) + "\x00c", s)
    # Markdown link: [text](url) -> \href{url}{text}
    s = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", lambda m: "\x00H" + m.group(2) + "\x00h" + m.group(1) + "\x00H", s)
    s = _escape(s)
    # Replace markers with real LaTeX.
    s = s.replace("\x00B", r"\textbf{").replace("\x00b", "}")
    s = s.replace("\x00I", r"\emph{").replace("\x00i", "}")
    s = s.replace("\x00C", r"\texttt{").replace("\x00c", "}")
    s = s.replace("\x00H", r"\href{").replace("\x00H", r"\href{")
    # Restore math segments.
    def restore_math(m: re.Match) -> str:
        idx = int(m.group(1))
        return math_segments[idx]
    s = re.sub(r"\x00M(\d+)\x00m", restore_math, s)
    return s


def _image_is_wide(img_path: str, base_dir: Path | None = None) -> bool:
    """Column-span judgement for a figure: True when the image's
    aspect ratio (w/h) is >= 1.8, i.e. it would be unreadably small
    in a single column and should span both (``figure*``).
    Unresolvable images default to single-column."""
    candidates = [Path(img_path)]
    if base_dir is not None:
        candidates.append(Path(base_dir) / img_path)
    for p in candidates:
        if not p.is_file():
            continue
        try:
            from PIL import Image
            with Image.open(p) as im:
                w, h = im.size
            return h > 0 and (w / h) >= 1.8
        except Exception:  # noqa: BLE001
            return False
    return False


def md_to_tex_body(md: str, base_dir: Path | None = None) -> tuple[str, str]:
    """Convert a markdown paper body to a (title, latex_body) pair.

    The body is everything between the top heading and the references
    block. Recognized:
      - ``# Title``
      - ``## Section``
      - ``### Subsection``
      - ``- item`` and ``1. item`` (lists)
      - paragraphs separated by blank lines
      - ``> blockquote``
      - fenced ```` ``` ```` blocks (rendered as verbatim)
    References (a ``## References`` section) are stripped and the
    citation list is returned separately via :func:`md_extract_refs`.
    The ``## Abstract`` section is also stripped: it is rendered in
    the preamble, not in the body.
    """
    lines = md.splitlines()
    title = ""
    body_lines: list[str] = []
    in_code = False
    in_refs = False
    in_abstract = False
    code_buf: list[str] = []
    list_buf: list[str] = []
    list_kind: str = ""

    def flush_list() -> None:
        nonlocal list_buf, list_kind
        if not list_buf:
            return
        if list_kind == "ol":
            body_lines.append(r"\begin{enumerate}")
        else:
            body_lines.append(r"\begin{itemize}")
        body_lines.extend(list_buf)
        if list_kind == "ol":
            body_lines.append(r"\end{enumerate}")
        else:
            body_lines.append(r"\end{itemize}")
        body_lines.append("")
        list_buf = []
        list_kind = ""

    skip_until = -1
    for i, raw in enumerate(lines):
        if i <= skip_until:
            continue
        line = raw.rstrip()
        if line.startswith("```"):
            if in_code:
                body_lines.append(r"\begin{verbatim}")
                body_lines.extend(code_buf)
                body_lines.append(r"\end{verbatim}")
                body_lines.append("")
                code_buf = []
                in_code = False
            else:
                flush_list()
                in_code = True
            continue
        if in_code:
            code_buf.append(line)
            continue
        if not line.strip():
            flush_list()
            continue
        # H1 title
        if line.startswith("# ") and not title:
            title = line[2:].strip()
            continue
        # Reference section -> stop here
        if line.startswith("## ") and "References" in line:
            flush_list()
            in_refs = True
            continue
        if in_refs:
            continue
        # Abstract section -> stop and skip (it's in the preamble)
        if line.startswith("## ") and "Abstract" in line:
            flush_list()
            in_abstract = True
            continue
        if in_abstract:
            # Skip lines until the next H2 (end of abstract).
            if line.startswith("## "):
                in_abstract = False
                # fall through to handle this H2 normally below
            else:
                continue
        # Section / subsection
        # Section / subsection
        if line.startswith("### "):
            flush_list()
            body_lines.append(r"\subsection*{%s}" % _md_inline_to_tex(line[4:].strip()))
            body_lines.append("")
            continue
        if line.startswith("## "):
            flush_list()
            body_lines.append(r"\section*{%s}" % _md_inline_to_tex(line[3:].strip()))
            body_lines.append("")
            continue
        # Markdown image: ![caption](path) -> figure or figure*.
        # Column-span judgement (per spec: large diagrams span both
        # columns): wide images (aspect ratio >= 1.8) go into
        # ``figure*`` at full text width so they stay readable; the
        # rest stay single-column.
        m_img = re.match(r"^!\[([^\]]*)\]\(([^)]+)\)\s*$", line)
        if m_img:
            flush_list()
            caption = _md_inline_to_tex(m_img.group(1).strip())
            img_path = m_img.group(2).strip()
            wide_fig = _image_is_wide(img_path, base_dir)
            fig_env = "figure*" if wide_fig else "figure"
            fig_width = r"0.85\textwidth" if wide_fig else r"0.9\linewidth"
            body_lines.append(rf"\begin{{{fig_env}}}[t]")
            body_lines.append(r"  \centering")
            body_lines.append(rf"  \includegraphics[width={fig_width}]{{{img_path}}}")
            body_lines.append(rf"  \caption{{{caption}}}")
            body_lines.append(rf"\end{{{fig_env}}}")
            body_lines.append("")
            continue
        # Markdown table: lines starting with `|` and the next line is
        # the `|---|---|` separator. Render as a `tabular`. The whole
        # contiguous block is consumed here (``skip_until``), so table
        # rows are never re-processed as paragraphs.
        if line.lstrip().startswith("|"):
            flush_list()
            k = i
            tbl_lines: list[str] = []
            while k < len(lines) and lines[k].lstrip().startswith("|"):
                tbl_lines.append(lines[k].rstrip())
                k += 1
            skip_until = k - 1
            # Parse: first line = header, second = sep, rest = rows
            if len(tbl_lines) >= 2 and re.match(r"^\s*\|[\s\-:|]+\|\s*$", tbl_lines[1]):
                header = [c.strip() for c in tbl_lines[0].strip().strip("|").split("|")]
                rows = [
                    [c.strip() for c in r.strip().strip("|").split("|")]
                    for r in tbl_lines[2:]
                ]
                col_spec = "l" * len(header)
                # Wide tables (>= 5 columns or long cells) span both
                # columns (`table*`) and are shrunk to the text width
                # so they can NEVER cross the page margin.
                est_width = max(
                    sum(len(c) for c in header),
                    max((sum(len(c) for c in r) for r in rows), default=0),
                )
                wide = len(header) >= 5 or est_width > 60
                env = "table*" if wide else "table"
                box = r"\textwidth" if wide else r"\columnwidth"
                body_lines.append(rf"\begin{{{env}}}[t]")
                body_lines.append(r"  \centering")
                body_lines.append(r"  \small")
                body_lines.append(rf"  \resizebox{{{box}}}{{!}}{{%")
                body_lines.append(rf"  \begin{{tabular}}{{{col_spec}}}")
                body_lines.append(r"    \hline")
                body_lines.append(
                    "    " + " & ".join(_md_inline_to_tex(c) for c in header) + r" \\ \hline"
                )
                for row in rows:
                    # Pad / trim ragged rows to the header width.
                    cells = (row + [""] * len(header))[:len(header)]
                    body_lines.append(
                        "    " + " & ".join(_md_inline_to_tex(c) for c in cells) + r" \\"
                    )
                body_lines.append(r"    \hline")
                body_lines.append(r"  \end{tabular}}")
                # Caption from the table's content (a dataset-stats
                # table must not be captioned "Measured results").
                header_l = {h.lower() for h in header}
                if {"method", "f1"} & header_l and "f1" in header_l:
                    caption = (
                        "Measured results (k = 3 seeds where stochastic; "
                        "best F1 per dataset in bold)."
                    )
                elif {"train", "test"} & header_l or "anomaly ratio" in header_l:
                    caption = "Dataset statistics (real public benchmarks)."
                else:
                    caption = "Summary."
                body_lines.append(rf"  \caption{{{caption}}}")
                body_lines.append(rf"\end{{{env}}}")
                body_lines.append("")
            else:
                # Not a real table; emit each line as a paragraph.
                for t in tbl_lines:
                    body_lines.append(_md_inline_to_tex(t))
                    body_lines.append("")
            continue
        # Block quote
        if line.startswith(">"):
            flush_list()
            body_lines.append(r"\begin{quote}")
            body_lines.append(_md_inline_to_tex(line.lstrip("> ").strip()))
            body_lines.append(r"\end{quote}")
            body_lines.append("")
            continue
        # List items
        m_ol = re.match(r"^(\d+)\.\s+(.+)$", line)
        m_ul = re.match(r"^[-*]\s+(.+)$", line)
        if m_ol:
            if list_kind != "ol":
                flush_list()
                list_kind = "ol"
            list_buf.append(r"\item " + _md_inline_to_tex(m_ol.group(2)))
            continue
        if m_ul:
            if list_kind != "ul":
                flush_list()
                list_kind = "ul"
            list_buf.append(r"\item " + _md_inline_to_tex(m_ul.group(1)))
            continue
        # Plain paragraph
        flush_list()
        body_lines.append(_md_inline_to_tex(line))
        body_lines.append("")
    flush_list()
    if in_code and code_buf:
        body_lines.append(r"\begin{verbatim}")
        body_lines.extend(code_buf)
        body_lines.append(r"\end{verbatim}")
    return title, "\n".join(body_lines)


def md_extract_refs(md: str) -> list[str]:
    """Pull the bullet list under a ``## References`` section as BibTeX-ish entries."""
    lines = md.splitlines()
    out: list[str] = []
    in_refs = False
    for line in lines:
        if line.startswith("## ") and "References" in line:
            in_refs = True
            continue
        if in_refs and line.startswith("## "):
            in_refs = False
        if not in_refs:
            continue
        m = re.match(r"^[-*]\s+(.+)$", line)
        if m:
            out.append(m.group(1).strip())
    return out


# ---- The .tex writer and pdflatex build ---------------------------------


def write_tex(
    paper_md: str, body_dir: Path, *,
    class_name: str = "acmart-sigconf",
    venue_id: str | None = None,
    venue_name: str | None = None,
    page_limit: int = 9,
) -> Path:
    """Emit ``paper.tex`` next to ``paper.md``. Returns the .tex path.

    The main body must fit within ``page_limit`` pages. If the body
    would overflow, we move the trailing sections to a separate
    ``paper_appendix.md`` (rendered as ``\\appendix``) so the main
    paper stays within the venue's limit. The appendix is
    redactor-checked so it does not contain ``src/`` file names or
    local PC paths.
    """
    body_dir = Path(body_dir)
    body_dir.mkdir(parents=True, exist_ok=True)
    title, body = md_to_tex_body(paper_md, base_dir=body_dir)
    refs = md_extract_refs(paper_md)
    # Page-limit enforcement: if the body is large, split to appendix.
    body, appendix_md, was_split = _enforce_page_limit(paper_md, body, page_limit)
    title_tex = _escape(title or "Paper")
    if venue_name:
        # "Target venue", not "Submitted to" — nothing has actually
        # been submitted, and the title must not claim otherwise.
        title_tex = _escape(f"[Target venue: {venue_name}] ") + title_tex
    if class_name == "acmart-sigconf":
        tex = NEURIPS_PREAMBLE_TEMPLATE % (
            title_tex,
            _md_inline_to_tex(_abstract_from_md(paper_md)),
        )
    else:
        tex = (
            _preamble_for_class(class_name)
            % (title_tex, _md_inline_to_tex(_abstract_from_md(paper_md)))
        )
    if venue_id and venue_id in _VENUE_NOTE:
        tex += f"% Venue note: {_VENUE_NOTE[venue_id]}\n"
    tex += f"% Page limit: {page_limit} (main text, excluding references)\n"
    tex += body
    if was_split and appendix_md.strip():
        # Append \appendix + redacted appendix content
        appendix_tex = md_to_tex_body(appendix_md)[1]
        appendix_tex = _redact_appendix(appendix_tex)
        tex += "\n\\appendix\n"
        tex += appendix_tex
    if refs:
        # Balance the two columns on the final page (avoids a long
        # left column next to an empty right one).
        if class_name == "acmart-sigconf":
            tex += "\n\\balance\n"
        tex += "\n\\begin{thebibliography}{99}\n"
        for i, r in enumerate(refs, 1):
            entry = re.sub(r"\*([^*]+)\*", r"\\emph{\1}", r)
            entry = re.sub(r"\[(\d+)\]\(([^)]+)\)", r"\\url{\2}", entry)
            tex += f"\\bibitem{{r{i}}} {entry}\n"
        tex += "\\end{thebibliography}\n"
    tex += NEURIPS_TAIL if class_name == "acmart-sigconf" else r"\end{document}" + "\n"
    out = body_dir / "paper.tex"
    out.write_text(tex, encoding="utf-8")
    # If we split, also write the appendix .md so the user can see it.
    if was_split and appendix_md.strip():
        (body_dir / "paper_appendix.md").write_text(
            "# Paper Appendix\n\n" + appendix_md, encoding="utf-8"
        )
    return out


# Rough heuristic: ~3000 chars per page in 2-column acmart layout.
_CHARS_PER_PAGE = 3000


def _enforce_page_limit(paper_md: str, body: str,
                        page_limit: int) -> tuple[str, str, bool]:
    """If ``body`` exceeds ~``page_limit`` pages, move trailing
    sections to the appendix.

    Returns ``(main_body, appendix_md, was_split)``. The split
    happens at the last ``## Section`` boundary that keeps the main
    body within the page budget. Sections already in the body
    stay; everything from the split point onward is the appendix.
    """
    if len(body) <= _CHARS_PER_PAGE * page_limit:
        return body, "", False
    # Find section boundaries in the body.
    sections = re.split(r"(?m)^## ", body)
    if len(sections) <= 1:
        # No sections to split; keep as-is.
        return body, "", False
    # Build progressively until we exceed the page budget, then
    # move the rest to the appendix.
    main = sections[0]
    appendix: list[str] = []
    for s in sections[1:]:
        candidate = main + "## " + s
        if len(candidate) > _CHARS_PER_PAGE * page_limit and main.strip():
            appendix.append(s)
        else:
            main = candidate
    if not appendix:
        return body, "", False
    appendix_md = "\n\n## ".join([""] + appendix).lstrip()
    return main, appendix_md, True


# Local-PC path / src-leak patterns the appendix redactor must strip.
_APPENDIX_FORBIDDEN_PATTERNS: tuple[tuple[re.Pattern[str], str], ...] = (
    (re.compile(r"[A-Za-z]:\\[^\s]*\.py", re.IGNORECASE), "[redacted:src path]"),
    (re.compile(r"workspace[\\/]src[\\/][^\s]*"), "[redacted:src path]"),
    (re.compile(r"/Users/[^\s]+"), "[redacted:local path]"),
    (re.compile(r"/home/[^\s]+"), "[redacted:local path]"),
)


def _redact_appendix(tex: str) -> str:
    """Strip src/ file names and local PC paths from the appendix.

    The user spec (req.txt) is explicit: 附录内不得出现src的代码名
    和本地电脑中与论文无关的信息. We pattern-match common forms
    and replace them with a redaction marker. The redactor is
    conservative — false positives are better than leaks.
    """
    out = tex
    for pat, repl in _APPENDIX_FORBIDDEN_PATTERNS:
        out = pat.sub(repl, out)
    return out


def _abstract_from_md(md: str) -> str:
    """Pull the body of the first ``## Abstract`` section.

    Strips any leading ``# Abstract`` sub-heading the LLM sometimes
    inserts (it does not know we already render the abstract as a
    preamble section, so it duplicates the title).
    """
    lines = md.splitlines()
    out: list[str] = []
    in_abs = False
    for line in lines:
        if line.startswith("## "):
            if in_abs:
                break
            if "Abstract" in line:
                in_abs = True
                continue
        if in_abs and line.strip():
            # Drop any in-section heading the LLM added (e.g. "# Abstract").
            if line.lstrip().startswith("#"):
                continue
            out.append(line)
    return " ".join(out).strip() or "(no abstract)"


def build_pdf(tex_path: Path, *, pdflatex_bin: str | None = None,
              timeout: float = 120.0,
              texinputs: Iterable[Path] | None = None) -> Path:
    """Run ``pdflatex`` on ``tex_path`` (twice, to resolve refs). Returns the .pdf path.

    Falls back gracefully:
      - If pdflatex is not on PATH, tries pandoc for a .docx.
      - If pandoc is also unavailable, returns a sentinel .pdf that
        does not exist (the caller treats the .md as canonical).
    """
    tex_path = Path(tex_path)
    if pdflatex_bin is None:
        pdflatex_bin = shutil.which("pdflatex")
    if not pdflatex_bin:
        # Common install locations when pdflatex is not on PATH.
        candidates: list[str] = [
            # Windows (TeX Live / MiKTeX)
            r"H:\texlive\2026\bin\windows\pdflatex.exe",
            r"C:\texlive\2026\bin\windows\pdflatex.exe",
            r"C:\Program Files\texlive\2026\bin\windows\pdflatex.exe",
            r"C:\Program Files\MiKTeX\miktex\bin\x64\pdflatex.exe",
            # macOS (MacTeX)
            "/Library/TeX/texbin/pdflatex",
            "/usr/local/texlive/2026/bin/universal-darwin/pdflatex",
            # Linux (TeX Live, distro or vanilla)
            "/usr/bin/pdflatex",
            "/usr/local/bin/pdflatex",
            "/usr/local/texlive/2026/bin/x86_64-linux/pdflatex",
            "/opt/texlive/2026/bin/x86_64-linux/pdflatex",
        ]
        for c in candidates:
            if Path(c).is_file():
                pdflatex_bin = c
                break
    if not pdflatex_bin:
        # Fallback: try pandoc to produce a .docx
        docx = _build_docx_via_pandoc(tex_path)
        if docx is not None:
            return docx
        # Last resort: keep the .md, raise a typed error so the
        # caller can surface "no LaTeX, no pandoc, .md is canonical".
        raise RuntimeError("pdflatex and pandoc are both unavailable; "
                           "the .md is the canonical paper artifact")
    cwd = tex_path.parent
    # Copy any custom .cls/.sty from the templates dirs into the
    # .tex cwd. This is the only reliable way to make a custom
    # class file findable without breaking the default kpsewhich
    # path for bundled classes (acmart, etc.).
    import shutil as _sh
    for src_dir in texinputs or []:
        src = Path(src_dir)
        if not src.is_dir():
            continue
        for child in src.iterdir():
            if child.is_file() and child.suffix in (".cls", ".sty", ".bst"):
                dst = cwd / child.name
                if not dst.exists():
                    _sh.copy2(child, dst)
    # Run twice to resolve \cite{} and \ref{} cross-references.
    last_err: subprocess.CalledProcessError | None = None
    for _ in range(2):
        try:
            subprocess.run(
                [pdflatex_bin, "-interaction=nonstopmode",
                 tex_path.name],
                cwd=str(cwd),
                check=True,
                capture_output=True,
                timeout=timeout,
            )
        except subprocess.CalledProcessError as exc:
            last_err = exc
            log = cwd / f"{tex_path.stem}.log"
            if log.is_file():
                tail = log.read_text(encoding="utf-8", errors="replace").splitlines()[-30:]
                logger.warning("pdflatex log tail:\n%s", "\n".join(tail))
            else:
                logger.warning("pdflatex stdout: %s", exc.stdout[-500:])
            # Don't break: try the second pass to see if it has the
            # same error, then return a sentinel. The .md remains
            # canonical.
            continue
    pdf = tex_path.with_suffix(".pdf")
    if pdf.is_file():
        return pdf
    # pdflatex failed (LLM emitted invalid LaTeX). Return the .tex
    # path as a sentinel so the pipeline can continue: the .md is
    # the canonical artifact. The caller (PhD's article_memo) will
    # record the failure.
    if last_err is not None:
        logger.warning(
            "pdflatex failed; returning .tex as canonical (no .pdf): %s",
            tex_path,
        )
    return tex_path


_LATEX_FIXUPS: tuple[tuple[re.Pattern[str], str], ...] = (
    # \Big/\bigg/\Bigg are not valid LaTeX; map to \big/\bigg/\Bigg
    # respectively. The LLM sometimes writes \Big{\lVert}.
    (re.compile(r"\\Big(\s*\{)"), r"\\big\1"),
    (re.compile(r"\\bigg(\s*\{)"), r"\\bigg\1"),
    # \text{}!{big} -> just remove the stray backslash-escape.
    (re.compile(r"\\text(asciicircum|textbar|textasciicircum)\{?\}?\s*!"),
    ""),
    # Math `\textbackslash{}!` -> empty (we just want the math).
    (re.compile(r"\\textbackslash\s*\{\}!?\s*"), ""),
)


def _fixup_latex(tex_path: Path) -> Path | None:
    """Apply small LaTeX rewrites to recover from common LLM typos.

    Returns the path to the rewritten .tex, or None on failure. The
    rewrite is in-place (we overwrite the .tex) so a follow-up
    pdflatex pass can read the corrected file.
    """
    try:
        text = tex_path.read_text(encoding="utf-8")
    except OSError:
        return None
    new_text = text
    for pattern, replacement in _LATEX_FIXUPS:
        new_text = pattern.sub(replacement, new_text)
    if new_text == text:
        return None
    tex_path.write_text(new_text, encoding="utf-8")
    return tex_path


def _build_docx_via_pandoc(tex_path: Path) -> Path | None:
    """Office fallback: produce a .docx via pandoc from the .md.

    The user spec (req.txt) says: 如果电脑没有就用office, markdown等.
    If pandoc is installed, we run ``pandoc -s paper.md -o paper.docx``
    and return the .docx path. The .docx is a valid Office file,
    even if the LaTeX template is not honored.
    """
    import os
    pandoc = shutil.which("pandoc")
    if not pandoc:
        # Try common install locations.
        for c in (
            r"C:\Program Files\Pandoc\pandoc.exe",
            r"H:\pandoc\pandoc.exe",
        ):
            if Path(c).is_file():
                pandoc = c
                break
    if not pandoc:
        return None
    md = tex_path.with_suffix(".md")
    if not md.is_file():
        return None
    docx = tex_path.with_suffix(".docx")
    try:
        # Pandoc supports .md -> .docx directly (we ignore the .tex).
        subprocess.run(
            [pandoc, "-s", str(md), "-o", str(docx)],
            check=True, capture_output=True, timeout=60,
        )
    except Exception:  # noqa: BLE001
        return None
    return docx


__all__ = [
    "build_pdf",
    "md_extract_refs",
    "md_to_tex_body",
    "write_tex",
]
